//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Permaculture_Animal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnimal
    {
        public int AnimalID { get; set; }
        public string AnimalName { get; set; }
        public string AnimalSex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime DeathDate { get; set; }
        public string BirthPlace { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public int SpeciesID { get; set; }
        public int DiseaseID { get; set; }
    
        public virtual tblDisease tblDisease { get; set; }
        public virtual tblSpecy tblSpecy { get; set; }
    }
}
